### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by razatg** [razatg/reworx#10]
- [x] Employee Refer emails,  Cc the recruiter. For From use Employee Name and email
- [x] Recruiter mail to Employee use Recruiter Name in From and and recruiter email

**Comment by pradipcoderockers** [comment]
Employee Refer emails, Cc the recruiter. For From use Employee Name and email
++ Done
 Recruiter mail to Employee use Recruiter Name in From and and recruiter email
++ Done
