### ISSUE TITLE
 Employee: Upload Contact

### ISSUE THREAD

**Issue by razatg** [razatg/reworx#4]
- [x] The BG image should be that, is present on the Home Page.

Learn More needs to be created.

**Comment by pradipcoderockers** [comment]
The BG image should be that, is present on the Home Page.
+++ Done

**Comment by razatg** [comment]
How do i check?

**Comment by pradipcoderockers** [comment]
Please use the below login detail access this section
Email : dheeraj1995singh@gmail.com
Pass : 12345678
while login this it will take you on csv upload section

**Comment by razatg** [comment]
- [ ] Store CSV then later ingest in DB

**Comment by pradipcoderockers** [comment]
Store CSV then later ingest in DB
+++ Done

**Comment by pradipcoderockers** [comment]
I have created two profile to check CSV upload Functionlity for testing
Email : pradip@onsinteractive.com
Pass : 12345678
Email : dheeraj1995singh@gmail.com
Pass : 12345678
and once csv uploaded hit below url to update to DB
http://demo.onsisdev.info/tracking/api/csvautomation.php
